name: flutter_structure
description: A structure for Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.0.0-218.0.dev <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
    # ios 图标库
  cupertino_icons: ^1.0.2
  # getx
  get: ^4.6.5
  # 日期格式
  intl: ^0.18.0
  # loaing
  flutter_easyloading: ^3.0.0
  # http
  dio: ^4.0.0
  cookie_jar: ^3.0.1
  dio_cookie_manager: ^2.0.0
  # storage + cache
  shared_preferences: ^2.0.6
  cached_network_image: ^3.0.0
  # 上拉刷新/下拉加载
  pull_to_refresh: ^2.0.0
  # webview
  webview_flutter: ^4.0.2
  # 拍照/图片 相关
  image_picker: ^0.8.6+1
  permission_handler: ^10.2.0
  photo_view: ^0.14.0
#  image_gallery_saver: ^1.7.1
  flutter_cache_manager: ^3.1.0

flutter:

  uses-material-design: true

  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700

